### ISSUE TITLE
Need escape quotes

### ISSUE THREAD

**Issue by claudiosmweb** [rasmusbe/gulp-wp-pot#11]
![screen_shot_2015-11-16_at_16 37 20](https://cloud.githubusercontent.com/assets/1264099/11188206/dfa8d400-8c70-11e5-8c8a-fd0cfa5d694a.png)

**Comment by rasmusbe** [comment]
I thought I had fixed this in 1.0.7, could you please verify that you are using the latest version (1.1.0).

**Comment by claudiosmweb** [comment]
Tested with 1.1.0.

**Comment by rasmusbe** [comment]
Thank you! I have found the bug and released version 1.1.1 with a fix.

**Comment by claudiosmweb** [comment]
Thanks, tested and works great :)
Good job!
