### ISSUE TITLE
Encoding issue (with poedit)

### ISSUE THREAD

**Issue by reeslo** [rasmusbe/gulp-wp-pot#16]
Hi,

The problem is with latin chars
```php
_e('Voici quelques liens pour vous aider à démarrer', 'domain');
```

POT headers
```pot
"Project-Id-Version: some-project\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2016-MO-DA HO:MI+ZONE\n"
"X-Poedit-Basepath: ..\n"
"X-Poedit-SourceCharset: UTF-8\n"
"X-Poedit-KeywordsList: __;_e;_n:1,2;_x:1,2c;_ex:1,2c;_nx:4c,1,2;esc_attr__;esc_attr_e;esc_attr_x:1,2c;esc_html__;esc_html_e;esc_html_x:1,2c;_n_noop:1,2;_nx_noop:3c,1,2;__ngettext_noop:1,2\n"
"X-Poedit-SearchPath-0: .\n"
"X-Poedit-SearchPathExcluded-0: *.js\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n\n"
```

I use Netbeans, so all source files are in utf-8 without BOM by default.

When I update the .po with the .pot poedit
![poedit-error](https://cloud.githubusercontent.com/assets/2724844/14225028/16b5e988-f8b4-11e5-9c94-33007d2e1344.png)
![poedit-error-results](https://cloud.githubusercontent.com/assets/2724844/14225029/1eaa9a12-f8b4-11e5-87f4-d8065e1fd5fc.png)

**Comment by rasmusbe** [comment]
I tried with your example string and it seems to work for me so I am unfortunately unable to repeat your problem.

I have attached the file, the gulp-file and the pot-file generated by gulp-wp-pot.

Please tell me if you can open the pot-file I have generated in your version of poedit.
And if you can, please try generating it again on your computer and send me the broken pot-file.

[gulp-wp-pot-test.zip](https://github.com/rasmusbe/gulp-wp-pot/files/201501/gulp-wp-pot-test.zip)

**Comment by reeslo** [comment]
Sorry for no reply, I am going to check that this week-end.

**Comment by reeslo** [comment]
I have no issue with your original filme, and after rebuild.
For me it's the same, if I build .pot only with file containing this string (onlly) It work perfectly.

Bad pot containing all translations
[bad-pot.zip](https://github.com/rasmusbe/gulp-wp-pot/files/211131/bad-pot.zip)

Good pot containing 2 strings..
[good-pot.zip](https://github.com/rasmusbe/gulp-wp-pot/files/211132/good-pot.zip)

Maybe mixed language ? Strange...

**Comment by rasmusbe** [comment]
I tried your bad pot file and it works fine for me in poedit 1.8.7, what version are you using?
Seems like poedit added support for non-english source languages in 1.8

**Comment by rasmusbe** [comment]
I'm closing this now. If you continue to have problem with the latest version of PoEdit don't hesitate to open this issue again.

**Comment by reeslo** [comment]
I am sorry for no reply quickly...

I am using Poedit 1.5.4, you are right.

Thank you !
