### ISSUE TITLE
constant as domain

### ISSUE THREAD

**Issue by geminorum** [rasmusbe/gulp-wp-pot#18]
How about constants as domain?

I'm usually: `_x( 'text, 'context', PLUGIN_TEXTDOMAIN );`

Instead of  `_x( 'text, 'context', 'plugin-textdomain' );`

**Comment by rasmusbe** [comment]
Just set domain to PLUGIN_TEXTDOMAIN, it should work. See this test for reference https://github.com/rasmusbe/gulp-wp-pot/blob/master/test.js#L233
