### ISSUE TITLE
Domain option should not be required

### ISSUE THREAD

**Issue by EmilEriksen** [rasmusbe/gulp-wp-pot#20]
In you documentation you state that domain can be omitted to scan for all textdomains but the plugin will throw an error if the domain options is not defined.
https://github.com/rasmusbe/gulp-wp-pot/blob/1a27316e4601400b5712baac1322a31c204d7c83/index.js#L257

**Comment by rasmusbe** [comment]
Thanks, I made it required by mistake when I changed the file name logic. Fixed now.

**Comment by EmilEriksen** [comment]
Awesome! Otherwise this is a great little tool!
