### ISSUE TITLE
Poedit error: Duplicate message definition

### ISSUE THREAD

**Issue by reefki** [rasmusbe/gulp-wp-pot#21]
After generate the .POT file and open it with Poedit by selecting "Create new translation", the file won't be opened and returns following errors:

```
Mon Jul 18 03:24:07 2016: /var/folders/vj/mtrbj91j6hgdgcbcwkqn_51m0000gn/T/poeditLwzPFK/0ref.pot:534: duplicate message definition...
Mon Jul 18 03:24:07 2016: /var/folders/vj/mtrbj91j6hgdgcbcwkqn_51m0000gn/T/poeditLwzPFK/0ref.pot:311: ...this is the location of the first definition
Mon Jul 18 03:24:07 2016: msgmerge(2871,0x7fff785f0000) malloc: *** error for object 0x7fbef8414a20: pointer being freed was not allocated
Mon Jul 18 03:24:07 2016: *** set a breakpoint in malloc_error_break to debug
```

When I select "Edit a translation" it can be opened but I got notification that duplicated translation string found and Poedit automatically fixed that.

My Poedit version 1.8.8

**Comment by rasmusbe** [comment]
Hi,

Could you please attach the pot-file so I can take a look at it.

/Rasmus

**Comment by reefki** [comment]
Hi @rasmusbe,

Sorry for delayed reply, here is the pot file.

P.S: I couldn't upload .pot so I changed the extension to .txt instead.
[writsy.txt](https://github.com/rasmusbe/gulp-wp-pot/files/390400/writsy.txt)

**Comment by rasmusbe** [comment]
Thank you, I see why it breaks and it's a bit tricky to fix, but I will soon

**Comment by rasmusbe** [comment]
Should be solved in 1.3.0

**Comment by AleCss81** [comment]
Hi, I have the same problem. I can't crete a translation because I receive a duplicate message definition error. How can I resolve this? My .pot file is from a template and the template team says there's no error inside this .pot file

Can you help me please? Thanks

**Comment by rasmusbe** [comment]
Which version of gulp-wp-pot did you use to generate the pot-file? And could you attach the pot file here please.

**Comment by AleCss81** [comment]
I'm using poedit and the version is 2.0.4
[x.zip](https://github.com/rasmusbe/gulp-wp-pot/files/1490668/x.zip)

**Comment by rasmusbe** [comment]
Sorry but If you didn't generate the pot with gulp-wp-pot I can't help you, then you have to contact the Poedit support team.
