### ISSUE TITLE
Not finding any translations

### ISSUE THREAD

**Issue by jcb121** [rasmusbe/gulp-wp-pot#25]
Hi, I have a pretty basic project setup.

Gulp version 3.9.1
Node version 6.5.0

`src/`
`dist/`
`gulpfile.js`

using the sample task
`gulp.task('pot', function () {`
`    return gulp.src('src/*.php')`
`        .pipe(sort())`
`        .pipe(wpPot( {`
`            domain: 'XXXX',`
`            destFile:'file.pot',`
`            package: 'XXXX',`
`            bugReport: 'http://example.com',`
`            lastTranslator: 'John Doe <mail@example.com>',`
`            team: 'Team Team <mail@example.com>'`
`        } ))`
`        .pipe(gulp.dest('dist'));`
`});`

It generates the file.pot but it's empty of translations

`# Copyright (C) 2016 XXXX
# This file is distributed under the same license as the XXXX package.
msgid ""
msgstr ""
"Project-Id-Version: XXXX\n"
"Report-Msgid-Bugs-To: http://example.com\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2016-MO-DA HO:MI+ZONE\n"
"Last-Translator: John Doe <mail@example.com>\n"
"Language-Team: Team Team <mail@example.com>\n"
"X-Poedit-Basepath: ..\n"
"X-Poedit-SourceCharset: UTF-8\n"
"X-Poedit-KeywordsList: __;_e;_n:1,2;_x:1,2c;_ex:1,2c;_nx:4c,1,2;esc_attr__;esc_attr_e;esc_attr_x:1,2c;esc_html__;esc_html_e;esc_html_x:1,2c;_n_noop:1,2;_nx_noop:3c,1,2;__ngettext_noop:1,2\n"
"X-Poedit-SearchPath-0: .\n"
"X-Poedit-SearchPathExcluded-0: *.js\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"`

I've used poedit to open the file and it finds no translations. it'll then search the directory and populate the file.

is there an incompatibility with the newer node/gulp version?

**Comment by rasmusbe** [comment]
I'm using the same versions and it works fine.
Could you include an example php file including some translation-methods that does not work?

**Comment by jcb121** [comment]
I redownloaded the package again using NPM and now it seems to be working.

Thanks a lot for this plugin!
Jesse.
