### ISSUE TITLE
Support for i18n themes and plugins name and descriptions

### ISSUE THREAD

**Issue by shvlv** [rasmusbe/gulp-wp-pot#40]
Wordpress tool makepot.php parse also comments in main plugin file and theme style.css. So fields 'Plugin/theme name', 'Plugin/theme url', 'Description' also add to pot file.

Maybe consider add this functional to you tool?

**Comment by rasmusbe** [comment]
Sounds like a good idea, I will look into it in the future. Help is much appreciated if someone got a good solution for this.

**Comment by shvlv** [comment]
I'm not very expirience in node.js but maybe some code can be adapted from project https://github.com/cedaro/grunt-wp-i18n/blob/develop/docs/makepot.md?

**Comment by geminorum** [comment]
- I think we need an option for type of the project. wp-i18n-tools calls it `addon` ([makepot.php#L401](https://github.com/ocean90/wp-i18n-tools/blob/master/makepot.php#L401))
- then based on the type, wp-pot must fill certain fields like: `version`, `author`, `name` and `slug` ([makepot.php#L490](https://github.com/ocean90/wp-i18n-tools/blob/master/makepot.php#L490) and [makepot.php#L531](https://github.com/ocean90/wp-i18n-tools/blob/master/makepot.php#L531))
- also theme template files `Template Name` ([makepot.php#L540](https://github.com/ocean90/wp-i18n-tools/blob/master/makepot.php#L540))

**Comment by rasmusbe** [comment]
Fixed in 2.0.5 with latest wp-pot.

Added option `metadataFile` to scan for version, author and name. The file must be within the src, so for themes the style.css must be included in the task.

All files in src is scanned for Template Name meta data.
