### ISSUE TITLE
Hi author.

### ISSUE THREAD

**Issue by rufus87novembit** [rasmusbe/gulp-wp-pot#52]
Could you please update required wp-pot version to latest one. 
Right now it is set to "^1,3,3"

But you updated the version of wp-pot to 1,3,4.

Please see [this](https://github.com/rasmusbe/wp-pot/issues/22) closed issue.

Thanks for your hard work.

**Comment by rasmusbe** [comment]
Hi,

Since 1.3.4 is allowed within the version span you can run `npm --depth 9999 update` to update wp-pot within your project.

Best regards,
Rasmus

**Comment by rufus87novembit** [comment]
thanks for information.
