### ISSUE TITLE
Incompatible with gulp 4 (as of 12/21/2017)

### ISSUE THREAD

**Issue by dsifford** [rasmusbe/gulp-wp-pot#56]
Gulp 4 now requires the latest version of `vinyl-fs`. It appears that you're using `gulp-utils` in this plugin which is now [recommended against](https://github.com/gulpjs/gulp/issues/2065#issuecomment-353624015).

Any chance you can refactor so that gulp 4 users can still use this?

Thanks!

**Comment by rasmusbe** [comment]
Good catch, I'll look into it, it should probably be quite easy
