### ISSUE TITLE
It doesn't extract Plugin Description from the main plugin file

### ISSUE THREAD

**Issue by widoz** [rasmusbe/gulp-wp-pot#87]
Differently than https://i18n.svn.wordpress.org/tools/trunk/ seems wp-pot doesn't include in the pot file the plugin description. 

Am I missing something in the configuration?

**Comment by widoz** [comment]
Sorry I found later the #40 gonna to close this.

**Comment by widoz** [comment]
I read #40 but sounds like the support for `description` has not been implemented.

**Comment by rasmusbe** [comment]
It should support `Description`.
https://github.com/rasmusbe/wp-pot/blob/master/translation-parser.js#L366

**Comment by widoz** [comment]
Hi @rasmusbe Thanks for the advice, I saw it. 
I found my mistake, the `metadataFile` should not contain the absolute path, just the file name where the `relativeTo` will contain only the parent folder of that file.
